# Pull base image
FROM python:3.8.12-slim

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Install dependencies
COPY fast /fast
COPY requirements_api.txt /requirements_api.txt

#upgrade libpq and install build tools, then build psycopg2-binary from source
RUN apt update -y && apt install -y build-essential libpq-dev \
&& pip install psycopg2-binary --no-binary psycopg2-binary \
&& pip install --upgrade pip \
&& pip install -r requirements_api.txt

EXPOSE 8000

CMD uvicorn fast.api:app --host 0.0.0.0