version: '3.8'

services:

  db:
      container_name: pg_container
      image: postgres
      restart: always
      env_file:
        - database.env
      ports:
        - "5432:5432"
      volumes:
        - /Users/michieldekoninck/code/Michiel-DK/tracker/database_dump/tracker.dump:/infile
        - pg_data:/var/lib/postgresql/data/

  api:
    container_name: api_container
    build: .
    volumes:
      - .:/api
    env_file:
      - database.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure

volumes:
  pg_data: