import psycopg2
from tracker.postgres import connect, config


def create_tables():
    """ create tables in the PostgreSQL database"""
    commands = (
        """
        CREATE TABLE yearly_financials (
                index BIGINT,
                year BIGINT,
                accountspayable BIGINT,
                assetturnover REAL,
                capitalexpenditures BIGINT,
                capitalsurplus BIGINT,
                cash BIGINT,
                cashdebt REAL,
                cashflow BIGINT,
                changeincash BIGINT,
                changetoaccountreceivables BIGINT,
                changetoinventory BIGINT,
                changetoliabilities BIGINT,
                changetonetincome BIGINT,
                changetooperatingactivities BIGINT,
                commonstock BIGINT,
                currentratio REAL,
                debtequity REAL,
                deferredlongtermassetcharges BIGINT,
                deferredlongtermliab BIGINT,
                depreciation BIGINT,
                dividendspaid BIGINT,
                earnings BIGINT,
                effectofexchangerate BIGINT,
                equityasset REAL,
                equitymultipl REAL,
                fcf BIGINT,
                fcfmargin REAL,
                financialleverage REAL,
                goodwill BIGINT,
                goodwillassets REAL,
                intangibleassets BIGINT,
                inventory BIGINT,
                investments BIGINT,
                issuanceofstock BIGINT,
                longtermdebt BIGINT,
                longterminvestments BIGINT,
                minorityinterest BIGINT,
                netborrowings BIGINT,
                netincome BIGINT,
                netmargin REAL,
                netreceivables BIGINT,
                nettangibleassets BIGINT,
                operatingmargin REAL,
                otherassets BIGINT,
                othercashflowsfromfinancingactivities BIGINT,
                othercashflowsfrominvestingactivities BIGINT,
                othercurrentassets BIGINT,
                othercurrentliab BIGINT,
                otherliab BIGINT,
                otherstockholderequity BIGINT,
                propertyplantequipment BIGINT,
                receivablessales REAL,
                repurchaseofstock BIGINT,
                retainedearnings BIGINT,
                revenue BIGINT,
                roa REAL,
                roe REAL,
                roic REAL,
                shortlongtermdebt BIGINT,
                shortterminvestments BIGINT,
                ticker VARCHAR(8),
                totalassets BIGINT,
                totalcashflowsfrominvestingactivities BIGINT,
                totalcashfromfinancingactivities BIGINT,
                totalcashfromoperatingactivities BIGINT,
                totalcurrentassets BIGINT,
                totalcurrentliabilities BIGINT,
                totalliab BIGINT,
                totalstockholderequity BIGINT,
                treasurystock BIGINT,
                key VARCHAR (12) UNIQUE
        )
        """,
        """ CREATE TABLE yearly_moat (
                index INT,
                operatingmargin REAL,
                fcfmargin REAL,
                netmargin REAL,
                roa REAL,
                roe REAL,
                moatpercentage REAL,
                year INT,
                ticker VARCHAR(8),
                key VARCHAR (12) UNIQUE
        )
        """,
        """CREATE TABLE yearly_health (
                index INT,
                receivablessales REAL,
                currentratio REAL,
                financialleverage REAL,
                debtequity REAL,
                percentage REAL,
                year INT,
                ticker VARCHAR(8),
                key VARCHAR (12) UNIQUE
            )
        """,
        """CREATE TABLE quarterly_financials (
                index BIGINT,
                year VARCHAR(6),
                accountspayable BIGINT,
                assetturnover REAL,
                capitalexpenditures BIGINT,
                capitalsurplus BIGINT,
                cash BIGINT,
                cashdebt REAL,
                cashflow BIGINT,
                changeincash BIGINT,
                changetoaccountreceivables BIGINT,
                changetoinventory BIGINT,
                changetoliabilities BIGINT,
                changetonetincome BIGINT,
                changetooperatingactivities BIGINT,
                commonstock BIGINT,
                currentratio REAL,
                debtequity REAL,
                deferredlongtermassetcharges BIGINT,
                deferredlongtermliab BIGINT,
                depreciation BIGINT,
                dividendspaid BIGINT,
                earnings BIGINT,
                effectofexchangerate BIGINT,
                equityasset REAL,
                equitymultipl REAL,
                fcf BIGINT,
                fcfmargin REAL,
                financialleverage REAL,
                goodwill BIGINT,
                goodwillassets REAL,
                intangibleassets BIGINT,
                inventory BIGINT,
                investments BIGINT,
                issuanceofstock BIGINT,
                longtermdebt BIGINT,
                longterminvestments BIGINT,
                minorityinterest BIGINT,
                netborrowings BIGINT,
                netincome BIGINT,
                netmargin REAL,
                netreceivables BIGINT,
                nettangibleassets BIGINT,
                operatingmargin REAL,
                otherassets BIGINT,
                othercashflowsfromfinancingactivities BIGINT,
                othercashflowsfrominvestingactivities BIGINT,
                othercurrentassets BIGINT,
                othercurrentliab BIGINT,
                otherliab BIGINT,
                otherstockholderequity BIGINT,
                propertyplantequipment BIGINT,
                receivablessales REAL,
                repurchaseofstock BIGINT,
                retainedearnings BIGINT,
                revenue BIGINT,
                roa REAL,
                roe REAL,
                roic REAL,
                shortlongtermdebt BIGINT,
                shortterminvestments BIGINT,
                ticker VARCHAR(8),
                totalassets BIGINT,
                totalcashflowsfrominvestingactivities BIGINT,
                totalcashfromfinancingactivities BIGINT,
                totalcashfromoperatingactivities BIGINT,
                totalcurrentassets BIGINT,
                totalcurrentliabilities BIGINT,
                totalliab BIGINT,
                totalstockholderequity BIGINT,
                treasurystock BIGINT,
                key VARCHAR (16) UNIQUE
        )
        """,
        """ CREATE TABLE quarterly_moat (
                index INT,
                operatingmargin REAL,
                fcfmargin REAL,
                netmargin REAL,
                roa REAL,
                roe REAL,
                moatpercentage REAL,
                year VARCHAR(6),
                ticker VARCHAR(8),
                key VARCHAR (16) UNIQUE
        )
        """,
        """CREATE TABLE quarterly_health (
                index INT,
                receivablessales REAL,
                currentratio REAL,
                financialleverage REAL,
                debtequity REAL,
                percentage REAL,
                year VARCHAR(6),
                ticker VARCHAR(8),
                key VARCHAR (16) UNIQUE
            )
        """,
        """CREATE TABLE weekly_info (
                index BIGINT,
                date DATE,
                weekchange52 REAL,
                sandp52weekchange REAL,
                address1 TEXT,
                address2 TEXT,
                algorithm TEXT,
                annualholdingsturnover TEXT,
                annualreportexpenseratio TEXT,
                ask REAL,
                asksize BIGINT,
                averagedailyvolume10day BIGINT,
                averagevolume BIGINT,
                averagevolume10days BIGINT,
                beta REAL,
                beta3year TEXT,
                bid REAL,
                bidsize BIGINT,
                bookvalue REAL,
                category TEXT,
                circulatingsupply TEXT,
                city TEXT,
                companyofficers TEXT,
                country TEXT,
                currency TEXT,
                currentprice REAL,
                currentratio REAL,
                dateshortinterest BIGINT,
                dayhigh REAL,
                daylow REAL,
                debttoequity REAL,
                dividendrate REAL,
                dividendyield REAL,
                earningsgrowth REAL,
                earningsquarterlygrowth REAL,
                ebitda BIGINT,
                ebitdamargins REAL,
                enterprisetoebitda REAL,
                enterprisetorevenue REAL,
                enterprisevalue BIGINT,
                exdividenddate BIGINT,
                exchange TEXT,
                exchangetimezonename TEXT,
                exchangetimezoneshortname TEXT,
                expiredate TEXT,
                fax TEXT,
                fiftydayaverage REAL,
                fiftytwoweekhigh REAL,
                fiftytwoweeklow REAL,
                financialcurrency TEXT,
                fiveyearaveragereturn TEXT,
                fiveyearavgdividendyield REAL,
                floatshares BIGINT,
                forwardeps REAL,
                forwardpe REAL,
                freecashflow BIGINT,
                fromcurrency TEXT,
                fulltimeemployees BIGINT,
                fundfamily TEXT,
                fundinceptiondate TEXT,
                gmtoffsetmilliseconds TEXT,
                grossmargins REAL,
                grossprofits BIGINT,
                heldpercentinsiders REAL,
                heldpercentinstitutions REAL,
                impliedsharesoutstanding TEXT,
                industry TEXT,
                isesgpopulated boolean,
                lastcapgain TEXT,
                lastdividenddate BIGINT,
                lastdividendvalue REAL,
                lastfiscalyearend BIGINT,
                lastmarket TEXT,
                lastsplitdate BIGINT,
                lastsplitfactor TEXT,
                legaltype TEXT,
                logo_url TEXT,
                longbusinesssummary TEXT,
                longname TEXT,
                market TEXT,
                marketcap BIGINT,
                maxage BIGINT,
                maxsupply TEXT,
                messageboardid TEXT,
                morningstaroverallrating TEXT,
                morningstarriskrating TEXT,
                mostrecentquarter BIGINT,
                navprice TEXT,
                netincometocommon BIGINT,
                nextfiscalyearend BIGINT,
                numberofanalystopinions BIGINT,
                open REAL,
                openinterest TEXT,
                operatingcashflow BIGINT,
                operatingmargins REAL,
                payoutratio REAL,
                pegratio REAL,
                phone TEXT,
                premarketprice REAL,
                previousclose REAL,
                pricehint BIGINT,
                pricetobook REAL,
                pricetosalestrailing12months REAL,
                profitmargins REAL,
                quickratio REAL,
                quotetype TEXT,
                recommendationkey TEXT,
                recommendationmean REAL,
                regularmarketdayhigh REAL,
                regularmarketdaylow REAL,
                regularmarketopen REAL,
                regularmarketpreviousclose REAL,
                regularmarketprice REAL,
                regularmarketvolume BIGINT,
                returnonassets REAL,
                returnonequity REAL,
                revenuegrowth REAL,
                revenuepershare REAL,
                revenuequarterlygrowth TEXT,
                sector TEXT,
                sharesoutstanding BIGINT,
                sharespercentsharesout REAL,
                sharesshort BIGINT,
                sharesshortpreviousmonthdate BIGINT,
                sharesshortpriormonth BIGINT,
                shortname TEXT,
                shortpercentoffloat REAL,
                shortratio REAL,
                startdate TEXT,
                state TEXT,
                strikeprice TEXT,
                ticker TEXT,
                targethighprice REAL,
                targetlowprice REAL,
                targetmeanprice REAL,
                targetmedianprice REAL,
                threeyearaveragereturn TEXT,
                tocurrency TEXT,
                totalassets TEXT,
                totalcash BIGINT,
                totalcashpershare REAL,
                totaldebt BIGINT,
                totalrevenue BIGINT,
                tradeable boolean,
                trailingannualdividendrate REAL,
                trailingannualdividendyield REAL,
                trailingeps REAL,
                trailingpe REAL,
                trailingpegratio REAL,
                twohundreddayaverage REAL,
                volume BIGINT,
                volume24hr TEXT,
                volumeallcurrencies TEXT,
                website TEXT,
                yield TEXT,
                ytdreturn TEXT,
                zip TEXT,
                key VARCHAR (20) UNIQUE
        )"""
        )
    conn = None
    try:
        # read the connection parameters
        params = config()
        # connect to the PostgreSQL server
        conn = psycopg2.connect(**params)
        cur = conn.cursor()
        # create table one by one
        for command in commands:
            cur.execute(command)
        # close communication with the PostgreSQL database server
        cur.close()
        # commit the changes
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()


if __name__ == '__main__':
    create_tables()